### ISSUE TITLE
Remove `no-default-files`?

### ISSUE THREAD

**Issue by woodruffw** [trailofbits/gh-action-sigstore-python#15]
I'm not sure it makes sense for us to expose this CLI flag as an action setting -- the user can simply choose not to use any artifacts/assets if they don't care about the default file outputs.

Thoughts @tetsuo-cpp?

**Comment by tetsuo-cpp** [comment]
Yeah definitely. I copied a lot of those flags across without much thought. I think we can probably remove flags for stuff like customising the OIDC provider that we use/verify against too.
